version: 2

formats: []

conda:
    environment: rtd_environment.yml
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - doc
  
