name: sklmer_dev
channels:
  - defaults
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - pandas=0.25.1
  - pytest
  - pytest-cov
  - rpy2=2.9.4
  - r-lme4
  - r-lmertest
  - r-lsmeans
  - tzlocal
