name: sklmer_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - rpy2
  - r-lme4
  - r-lmertest
  - r-lsmeans
  - tzlocal
  - pip
  - sphinx
  - mock
  - pillow
  - sphinx_rtd_theme
  - matplotlib
  - pip:
    - pymer4
    - numpydoc
    - sphinx_gallery